### ISSUE TITLE
Feature Request: Sort Output by Complexity

### ISSUE THREAD

**Issue by NiklasvonM** [rohaquinlop/complexipy#27]
I'd like to propose adding the option to sort the output by the complexity, perhaps via an `-s`/`--sort` option.

When analyzing a large project for the first time, this could help finding the worst offenders quickly.

I suggest sorting the complexity in an ascending order by default since one sees the last entries first when printed to the terminal.

**Comment by rohaquinlop** [comment]
Thank you, @NiklasvonM this is a really useful

**Comment by rohaquinlop** [comment]
@NiklasvonM This feature is already implemented, will be present in the next release, thank you for your feedback
