### ISSUE TITLE
Consider support for older versions of Python

### ISSUE THREAD

**Issue by jmlemetayer** [rohaquinlop/complexipy#31]
I can't install `complexipy` on my `Ubuntu 22.04 LTS` as my python version is 3.10.

But `complexipy` requires python version >= 3.11.

However:
- Typer requires python 3.6+ (https://typer.tiangolo.com/#requirements)
- Maturin is supporting python 3.8+ (https://github.com/PyO3/maturin) 

Is there any reason why you force it to 3.11+? (https://github.com/rohaquinlop/complexipy/commit/e213ce8fd85768dca88d2186dc39efd1e56f9a15)

**Comment by rohaquinlop** [comment]
@jmlemetayer There's no reason why python >= 3.11 I just wanted to set a minimum version and thought that this could be a good choice because it was a stable one, but I will set it to >= 3.8 considering your comments, thank you for your feedback!

**Comment by rohaquinlop** [comment]
Solved
