### ISSUE TITLE
Expose library commands 

### ISSUE THREAD

**Issue by andrewdea** [rohaquinlop/complexipy#46]
Currently, the package is most useful as a CLI, but we cannot import most of its functionalities into python code.

I have created [this PR](https://github.com/rohaquinlop/complexipy/pull/45) to expose the most useful commands: 
 - `code_complexity` to compute the complexity of any snippet (string) of code
 - `file_complexity` to compute the complexity of a file

**Comment by rohaquinlop** [comment]
@andrewdea would be great if we have this functions in the documentation, if you want you can add it, or I can do it if you want to.

**Comment by andrewdea** [comment]
@rohaquinlop great point! I'll go ahead and add docs today

**Comment by andrewdea** [comment]
@rohaquinlop I think we can close this thanks to [the merge](https://github.com/rohaquinlop/complexipy/pull/45).

Once we have the docs done, we'll be ready for a new release? Just checking if there's any additional steps
